INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('LA', 'Lineare Algebra', 0, 1, 1, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('CABS', 'Computerarchitektur und Betriebssysteme', 0, 0, 1, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('MD1', 'Mediendesign 1', 0, 1, 1, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('EI', 'Einführung in die Informatik', 0, 1, 1, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('GP1', 'Grundlagen der Programmierung 1', 0, 1, 1, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('KFS', 'Kommunikation, Führung und Selbstmanagement', 0, 1, 1, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('RF', 'Relationen und Funktionen', 0, 1, 0, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('MCK', 'Mensch-Computer-Kommunikation', 0, 1, 0, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('MD2', 'Mediendesign 2', 0, 1, 0, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('TI', 'Theoretische Informatik', 0, 1, 0, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('GP2', 'Grundlagen der Programmierung 2', 0, 1, 1, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('KN1', 'Kommunikationsnetze 1', 0, 1, 0, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('CG', 'Computergrafik', 0, 0, 1, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('ADS', 'Algorithmen und Datenstrukturen', 0, 0, 1, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('WEB', 'Webprogrammierung', 0, 0, 1, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('DB', 'Datenbanken', 0, 0, 1, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('ITR', 'IT-Recht', 0, 0, 1, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('MMT', 'Multimediatechnik', 0, 0, 1, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('BWL', 'Betriebswirtschaftslehre', 0, 1, 0, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('EWP', 'Einführung in die wissenschaftliche Projektarbeit', 0, 1, 1, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('IMG', 'Internetanwendungen für mobile Geräte', 0, 1, 0, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('GIS', 'Grundlagen IT-Sicherheit', 0, 1, 0, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('SWT', 'Softwaretechnik', 0, 1, 0, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('ISP', 'Internet-Serverprogrammierung', 0, 1, 1, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('PFW', 'Patterns & Frameworks', 0, 0, 1, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('KN2', 'WPF - Kommunikationsnetze 2', 1, 0, 1, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('MWK', 'WPF - Medienwirtschaft und Kommunikationspolitik', 1, 0, 1, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('AKB', 'WPF - Ausgewählte Kapitel zu Betriebssystemen', 1, 0, 1, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('CPP', 'WPF - Programmierung in C++', 1, 1, 1, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('EPM', 'WPF - Einführung Projektmanagement', 1, 0, 1, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('CMS', 'WPF - Content-Management Systeme', 1, 0, 1, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('INM', 'Informationsmanagement', 0, 1, 0, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('OOS', 'WPF - Objektorientierte Skriptsprachen', 1, 1, 0, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('BBV', 'WPF - Bildbearbeitung und Bildverarbeitung', 1, 1, 0, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('RMA', 'WPF - Rich-Media-Anwendungen', 1, 1, 0, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('TEE', 'WPF - Technisches Englisch', 1, 0, 1, 5, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('PRO', 'Praxisprojekt', 0, 1, 1, 15, 'MINF');
INSERT INTO app_module (MID, Name, WPF, SS, WS, CP, discipline) VALUES ('BA', 'Bachelorarbeit', 0, 1, 1, 15, 'MINF');