# Generated by Django 2.2.1 on 2019-06-02 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('MID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('WPF', models.BooleanField(default=0)),
                ('SS', models.BooleanField(default=0)),
                ('WS', models.BooleanField(default=0)),
                ('CP', models.IntegerField(default=5)),
                ('discipline', models.CharField(choices=[('MINF', 'Medieninformatik'), ('WINF', 'Wirtschaftsinformatik')], default='MINF', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('userid', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('branch', models.CharField(choices=[('MINF', 'Medieninformatik'), ('WINF', 'Wirtschaftsinformatik')], default='MINF', max_length=4)),
                ('startingSemester', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module', to='app.Module')),
                ('prereq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite', to='app.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accredited', models.BooleanField(default=0)),
                ('score', models.FloatField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Student')),
            ],
        ),
    ]
