# Generated by Django 2.2.1 on 2019-05-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MID', models.CharField(max_length=4, unique=True)),
                ('Name', models.CharField(max_length=50)),
                ('WPF', models.BooleanField(default=0)),
                ('SS', models.BooleanField(default=0)),
                ('WS', models.BooleanField(default=0)),
                ('Branch', models.CharField(max_length=4, null=True)),
            ],
        ),
    ]
