# Generated by Django 2.2.1 on 2019-05-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Module',
            new_name='Modules',
        ),
    ]
