# Generated by Django 2.2.1 on 2019-06-07 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('discipline', models.CharField(choices=[('MINF', 'Medieninformatik'), ('WINF', 'Wirtschaftsinformatik')], default='MINF', max_length=4)),
                ('startingSemester', models.CharField(max_length=7)),
            ],
        ),
    ]
